[package]
name = "pvp-macro"
version = "0.0.1"
edition = "2021"

[dependencies]
fltk = "^1.4"
include_dir = "0.7.4"
webbrowser = "1.0.1"
rdev = "0.5.3"
rand = "0.8.5"

[profile.release]
opt-level ="z"
panic = "abort"
